### PR TITLE
Chore: adapt to api level 9

### PR DESCRIPTION
**Pull request by DakunesuD**
Adapt to Dalamud API level 9.

### CODE REVIEW

**Comment by DorkmasterFlek** [comment]
Resolves issue #278 opened for this.

**Comment by frukbachers** [comment]
I don't think attick is maintaining this anymore, would it be possible for you to fork and build it on your own?

**Comment by Draiven123** [comment]
> I don't think attick is maintaining this anymore, would it be possible for you to fork and build it on your own?
> 
> Edit: nevermind, just saw that there is a maintained version already. Let's see if attick will see your commit though, thanks from an unrelated person like me for your work.

Where is the maintained version?

**Comment by DakunesuD** [comment]
Do not merge, this commit no longer works.

**Comment by DakunesuD** [comment]
PR updated.

**Comment by syncmaster255** [comment]
> Adapt to Dalamud API level 9.

what does this mean?

**Pull request closed without merging**
