### PR TITLE
Fix Gyofu (again)

### LINKED ISSUE #319: SAM: Gyofu is broken again
Gyofu was fixed in 50f6f54ae012d9b622c8231c8e166b3374f1f4e9 but broken again in 0f1226be0b07f14f54fb90ba03af2e263d9433b9 and 7fcc73750a89f3b63105a2824689ac0d6791a50e

Is there some reason for this?

### PR DESCRIPTION
**Pull request by Vogelchevalier**
Fixes #319 

Feel free to decline if there's a reason for Gyofu being broken currently (is it being fixed some other way?)

### CODE REVIEW

**Comment by attickdoor** [comment]
🤔 I thought something had changed with action IDs, but it seems like it didn't change in the way I had imagined it.

**Comment by Skooz** [comment]
> 🤔 I thought something had changed with action IDs, but it seems like it didn't change in the way I had imagined it.

Oddly, Monk remains fine, despite only checking for the base IDs and not the upgraded ones.

Yet, MCH, SAM, and possibly some others broke...

**Comment by attickdoor** [comment]
For reasons that I don't understand, MCH doesn't have to check for upgraded states in lastMove, while SAM and DRG do.

**Comment by attickdoor** [comment]
Should be fixed now. I'll cut 1.8.2 in a bit.

**Pull request closed without merging**
